//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteInfo
    {
        public long id { get; set; }
        public string city { get; set; }
        public string title { get; set; }
        public string biketype { get; set; }
        public string geography { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
